config/routes.rb
Codewithus::Application.routes.draw do

  get 'signup'=> 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'skills_needed' => 'hackathons#skills_needed'

  get 'finish_account_signup' => "users#new_from_facebook"
  post 'finish_account_signup' => "users#create_from_facebook", :as => "finish_account_signup"

  post 'add_teammate' => 'teammates#add_teammate'

  match 'auth/facebook/callback', to: 'users#facebook_auth'
  get 'auth/failure', to: redirect('/')

  resources :users do 
    resources :user_skillcategories 
  end

  resources :hackathons do
    resources :teams
    resources :teammates
  end
  resources :sessions
  resources :charges
  resources :participants
  

  root :to => 'hackathons#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :cell, :email, :image, :image_content_type, :image_file_name, :name, :password, :password_confirmation

  has_secure_password
  # validates :password, :presence => { :on => :create }
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :participants
  has_many :hackathons, :through => :participants

  has_attached_file :image, :default_url => "avatar.jpg"
  validates_attachment_presence :image unless :image
  validates_attachment_content_type :image, :content_type => ['image/jpg', 'image/jpeg', 'image/png']

  has_many :user_skills
  has_many :skills, :through => :user_skills

  has_many :user_skillcategories
  has_many :skillcategories, :through => :user_skillcategories

  has_many :identities

  def self.from_facebook_omniauth(auth)
    user = User.where(:email => auth[:info][:email]).first_or_initialize
    
    # create user with default password
    user.password_digest = '$2a$10$hES1PybNlFkaGCh4ZlmlBOeRgJnnwQ3qLHuKbziZeO1/1XIpHTc5O'
    user.save

    identity = Identity.where(:uid => auth[:uid]).first_or_initialize

    # assign identity attributes
    identity.user = user
    identity.provider = auth[:provider]
    identity.uid = auth[:uid]
    identity.login_name = auth[:info][:nickname]
    identity.image = auth[:info][:image]
    identity.atoken = auth[:credentials][:token]
    identity.oauth_expires_at = Time.at(auth[:credentials][:expires_at])
    identity.save

    return user
  end

  def has_identity?
    self.identities.present?
  end

  def copy_identity_data(user)
    identity = user.identities.last
    identity.user = self
    identity.save
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :login_required, :only => ["new", "create", "facebook_auth"]


  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def edit
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    params[:user_skillcategory].each do |skill, level|
      skill = Skillcategory.find_by_name(skill)
      user_skill = @user.user_skillcategories.find_or_create_by_skillcategory_id(skill.id)
      user_skill.level = level
      user_skill.save
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user), :notice => "Profile updated!" }
        format.json { render json: @users }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :notice => "Sorry, your profile could not be updated."}
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def create
    @user = User.new(params[:user])
    @user.cell = @user.cell.gsub("-","").gsub(".","").gsub("(","").gsub(")","").gsub(" ","")

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to new_user_user_skillcategory_path(@user), notice: 'Now add your skills!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_from_facebook
    @user = current_user
  end

  def create_from_facebook
    if @user_exists = User.where(:email => params[:user][:email]).first
      @user_exists.copy_identity_data(current_user)
      current_user.delete
      session[:user_id] = @user_exists.id
      @user_exists.update_attributes(params[:user])
    else
      @user = current_user
      @user.update_attributes(params[:user])
      redirect_to root_url
    end
  end

  def facebook_auth
    auth_hash = request.env['omniauth.auth']
    user = User.from_facebook_omniauth(auth_hash)
    session[:user_id] = user.id
    redirect_to finish_account_signup_path
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cell %><br />
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :Upload_a_photo %><br />
    <%= f.file_field :image %>
  </div>

  <%= fields_for(@user.user_skillcategories.build) do |skills| %>

    <div class="field">
      <label>Design</label>
      <input type="range" min="1" max="3" name='user_skillcategory[Design]' value="<%= user_skillcategory_default(@user, 1) %>">
      <output id="output" for="user_skillcategory[Design]">1</output>
    <div>

    <div class="field">
      <label>Frontend</label>
      <input type="range" min="1" max="3" name='user_skillcategory[Front End]' value="<%= user_skillcategory_default(@user, 2) %>">
      <output id="output" for="user_skillcategory[Frontend]">1</output>
    <div>

    <div class="field">
      <label>Backend</label>
      <input type="range" min="1" max="3" name='user_skillcategory[Back End]' value="<%= user_skillcategory_default(@user, 3) %>">
      <output id="output" for="user_skillcategory[Backend]">1</output>
    <div>

  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Edit User</h3>

<%= render :partial => 'form' %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user|  %>
    <li><%= link_to user.name, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<p>Create a new account from facebook:<p>

<p><%= link_to "Facebook sign-up", "/auth/facebook" %><p>

<p>Or fill out this form:</p>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cell %><br />
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :Upload_a_photo %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new_from_facebook.html.erb
<%= form_tag finish_account_signup_path do %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field :user, :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field :user, :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br />
    <%= password_field :user, :password_confirmation %>
  </div>
  <div class="actions">
    <%= submit_tag("Create Account") %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= link_to "Edit Profile", edit_user_path(@user), :class => "btn" %>

<% if current_user.identities %>
  <div><%= image_tag facebook_pic %></div>
<% else %>
  <div><%= image_tag @user.image %></div>
<% end %>

<ul>
    <li><%= @user.name %></li>
    <li><%= @user.email %></li>
</ul>

Skills:
<ul>
   <%@user.user_skillcategories.each do |skill| %>
    <li><%= Skillcategory.where(:id => skill.skillcategory_id).first.name %> - <%= skill.level %> </li>
  <% end %>
</ul>

Hackathons:

<ul>
  <% @user.hackathons.each do |hackathon| %>
    <li><%= link_to(image_tag(hackathon.image), hackathon_path(hackathon)) %></li>
    <li><%= link_to(hackathon.name, hackathon_path(hackathon)) %></li>
    <li><%= hackathon.start %></li>
    <li><%= hackathon.location %></li>
    <li><%= hackathon.price %></li>
  <% end %>
</ul>