config/routes.rb
Codewithus::Application.routes.draw do

  get 'signup'=> 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'skills_needed' => 'hackathons#skills_needed'

  get 'finish_account_signup' => "users#new_from_facebook"
  post 'finish_account_signup' => "users#create_from_facebook", :as => "finish_account_signup"

  post 'add_teammate' => 'teammates#add_teammate'

  match 'auth/facebook/callback', to: 'users#facebook_auth'
  get 'auth/failure', to: redirect('/')

  resources :users do 
    resources :user_skillcategories 
  end

  resources :hackathons do
    resources :teams
    resources :teammates
  end
  resources :sessions
  resources :charges
  resources :participants
  

  root :to => 'hackathons#index'

end

app/models/teammate.rb
class Teammate < ActiveRecord::Base

  attr_accessible :team_id, :user_id
  before_save

  belongs_to :user
  belongs_to :team

end

app/controllers/teammates_controller.rb
class TeammatesController < ApplicationController
  # GET /teammates
  # GET /teammates.json
  def index
    @teammates = Teammate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teammates }
    end
  end

  # GET /teammates/1
  # GET /teammates/1.json
  def show
    @teammate = Teammate.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teammate }
    end
  end

  # GET /teammates/new
  # GET /teammates/new.json
  def new
    @teammate = Teammate.new
    @teams = Hackathon.find(params[:hackathon_id]).teams

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teammate }
    end
  end

  # GET /teammates/1/edit
  def edit
    @teammate = Teammate.find(params[:id])
  end

  # POST /teammates
  # POST /teammates.json
  def create
    @teammate = Teammate.new
    @teammate.team_id = params[:id]
    @teammate.user_id = current_user.id

    respond_to do |format|
      if @teammate.save
        format.html { redirect_to hackathon_path(Hackathon.find(params[:hackathon_id])), notice: 'Teammate was successfully created.' }
        format.json { render json: @teammate, status: :created, location: @teammate }
      else
        format.html { render action: "new" }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_teammate # Ajax post request
    @team = Team.find(params[:team_id])
    @team.teammates.build(:user_id => current_user.id)
    @team.save

    redirect_to hackathon_path(@team.hackathon)
    # render :text => "hello"
    # raise params.inspect
    # respond_to do |f|
    #   f.js { "teammates/add_teammate"}
    #   f.html {}
    # end
  end

  # PUT /teammates/1
  # PUT /teammates/1.json
  def update
    @teammate = Teammate.find(params[:id])

    respond_to do |format|
      if @teammate.update_attributes(params[:teammate])
        format.html { redirect_to @teammate, notice: 'Teammate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teammates/1
  # DELETE /teammates/1.json
  def destroy
    @teammate = Teammate.find(params[:id])
    @teammate.destroy

    respond_to do |format|
      format.html { redirect_to teammates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teammates_helper.rb
module TeammatesHelper
end

app/views/teammates/_form.html.erb
<%= form_for(@teammate, :url => hackathon_teammates_path) do |f| %>
  <% if @teammate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teammate.errors.count, "error") %> prohibited this teammate from being saved:</h2>

      <ul>
      <% @teammate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Which team would you like to join?" %>
    <%=  select_tag 'id', options_for_select(@teams.collect{ |t| [t.name, t.id] }) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/teammates/edit.html.erb
<h1>Editing teammate</h1>

<%= render 'form' %>

<%= link_to 'Show', @teammate %> |
<%= link_to 'Back', teammates_path %>

app/views/teammates/index.html.erb
<h1>Listing teammates</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teammates.each do |teammate| %>
  <tr>
    <td><%= link_to 'Show', teammate %></td>
    <td><%= link_to 'Edit', edit_teammate_path(teammate) %></td>
    <td><%= link_to 'Destroy', teammate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teammate', new_teammate_path %>

app/views/teammates/new.html.erb
<h1>New teammate</h1>

<%= render 'form' %>

app/views/teammates/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_teammate_path(@teammate) %> |
<%= link_to 'Back', teammates_path %>