config/routes.rb
Codewithus::Application.routes.draw do

  get 'signup'=> 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'skills_needed' => 'hackathons#skills_needed'

  get 'finish_account_signup' => "users#new_from_facebook"
  post 'finish_account_signup' => "users#create_from_facebook", :as => "finish_account_signup"

  post 'add_teammate' => 'teammates#add_teammate'

  match 'auth/facebook/callback', to: 'users#facebook_auth'
  get 'auth/failure', to: redirect('/')

  resources :users do 
    resources :user_skillcategories 
  end

  resources :hackathons do
    resources :teams
    resources :teammates
  end
  resources :sessions
  resources :charges
  resources :participants
  

  root :to => 'hackathons#index'

end

app/models/hackathon.rb
class Hackathon < ActiveRecord::Base
  attr_accessible :capacity, :description, :end, :image, :image_content_type, :image_file_name, :location, :name, :price, :start

  has_many :participants
  has_many :users, :through => :participants
  has_many :teams

  accepts_nested_attributes_for :teams

  has_attached_file :image, :default_url => "avatar.jpg"
  validates_attachment_presence :image unless :image
  validates_attachment_content_type :image, :content_type => ['image/jpg', 'image/jpeg', 'image/png']

  def user_participating?(user)
    true if self.teams.any? { |team| team.teammates.any? { |teammate| teammate.user_id == user.id }}
  end

  def participating_users
    self.teams.collect { |team| team.teammates }.flatten.collect { |teammate| teammate.user_id }.uniq
  end

  def potential_teammates
    User.all.collect { |user| user.id } - self.participating_users
  end

  def load_potential_teammates(user)
    self.potential_teammates.collect { |id| User.find(id) } - [user]
  end

end

app/controllers/hackathons_controller.rb
class HackathonsController < ApplicationController

  skip_before_filter :login_required, :only => ["index"]

  # GET /users
  # GET /users.json

  # def skills_needed
  #   render :partial => "new_hackathon_team"
  # end

  def logistics
    render :partial => "new_logistics"
  end

  def index
    @search = Hackathon.search(params[:q])
    @hackathons = @search.result.order("start DESC")
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @hackathon = Hackathon.find(params[:id])
    @teammate = Teammate.new
    @participant= @hackathon.participants.build(:user_id => current_user.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hackathon }
    end
  end

  def new
    @hackathon = Hackathon.new
    @team = @hackathon.teams.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hackathon }
    end
  end

  # GET /stars/1/edit
  def edit
    @hackathon = Hackathon.find(params[:id])
  end

  def create
    @hackathon = Hackathon.new(params[:hackathon])
    @team = @hackathon.teams.build(:name => params[:team][:name])
    params[:team][:teammates].each do |teammate_id|
      unless @team.teammates.any? { |teammate| teammate.id == teammate_id }
        user = User.find(teammate_id)
        @team.teammates.build(:user_id => user.id)
      end
    end

    respond_to do |format|
      if @hackathon.save
        format.html { redirect_to @hackathon, notice: 'Hackathon was successfully created.' }
        format.json { render json: @hackathon, status: :created, location: @hackathon }
      else
        format.html { render action: "new" }
        format.json { render json: @hackathon.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @hackathon = Hackathon.find(params[:id])

    respond_to do |format|
      if @hackathon.update_attributes(params[:star])
        format.html { redirect_to @hackathon, notice: 'Hackathon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hackathon.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @hackathon = Hackathon.find(params[:id])
    @hackathon.destroy

    respond_to do |format|
      format.html { redirect_to stars_url }
      format.json { head :no_content }
    end
  end

end

app/views/hackathons/_hackathons_index.html.erb
<% hackathons.each do |hackathon|  %>
  <div class="hackathon">
    <div>
      <h1><%= link_to hackathon.name, hackathon %></h1>
      <time><%= link_to hackathon.start.to_formatted_s(:long), hackathon, class: "time-blue-block" %><time>
        <a href="<%= hackathon_path(hackathon) %>" class="hackathon-image">
        <img src="<%= hackathon.image %>">
      </a>
    </div>
    <div>
      <p class="location">
        <%= hackathon.location %>
      </p>
      <p class="count">
        <%= hackathon.participating_users.count %> people 
      </p> |
      <p class="count">
        <%= hackathon.teams.count %> teams 
      </p>
    </div>
    <div>
      <a href="<%= hackathon_path(hackathon) %>" class="view-blue-block">Join Hackathon
      </a>
    </div>  
  </div>
<% end %>

app/views/hackathons/_new_hackathon_team.html.erb
<h1>Add Hackathon Team</h1>

app/views/hackathons/_new_logistics.html.erb
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :location %><br />
  <%= f.text_field :location %>
</div>

<div class="field">
  <%= f.label :start %><br />
  <%= f.datetime_select :start, :ampm => true, :minute_step => 15 %>
</div>

<div class="field">
  <%= f.label :end %><br />
  <%= f.datetime_select :end, :ampm => true, :minute_step => 15 %>
</div>

<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</div>

<div class="field">
  <%= f.label :capacity %><br />
  <%= f.number_field :capacity %>
</div>

<div class="field">
  <%= f.label :price %><br />
  <%= f.number_field :price %>
</div>

<div class="field">
  <%= f.label :Upload_a_photo %><br />
  <%= f.file_field :image %>
</div>

app/views/hackathons/index.html.erb
<section>
  <%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :location, "Location" %>
    <%= f.text_field :location_cont %>
  </div>
  <div class="actions">
    <%= f.submit "Search" %>
  </div>
<% end %>
</section>

<%= render :partial => "hackathons_index", :locals => {:hackathons => @hackathons} %>

app/views/hackathons/new.html.erb
<div id="new_hackathon_container">
  <ul id="new_hackathon_nav">
    <li>
      <%= link_to "Logistics", "#", :controller => "hackathons", :action => "skills_needed", :id => "logistics" %>
    </li>
    <li>
      <%= link_to "Skills", "#", :controller => "hackathons", :action => "skills_needed", :id => "skills_needed" %>
    </li>
    <li>
      <%= link_to "Friends", "#", :controller => "hackathons", :action => "skills_needed", :id => "friends" %>
    </li>
  </ul>
  <br><br>
  <input type='text' id='datepicker' value="<%= Date.today.to_s %>">

  <%= form_for(@hackathon) do |f| %>
    <% if @hackathon.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@hackathon.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @hackathon.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div id="content">

    <%= render :partial => "new_logistics", :locals => { :f => f } %>
    <br>
    <%= fields_for @team do |t| %>
      <%= t.label :name %>
      <%= t.text_field :name %>
      <%= t.label "Teammates" %>
      <div class="teammate">
        <select name="team[teammates][]">
        <%= options_from_collection_for_select(User.all, :id, :name) %>
        </select>
        <br>
      </div>
      <button id="add_teammate">Add a Teammate</button>
    <% end %>

    </div>
    <br>
    <div class="actions">
      <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/hackathons/show.html.erb
<section>
  <div class="row-fluid">
    <div class="span7 header-content">
      <span class="pull-left">
        <%= pluralize(@hackathon.teams.size, 'team') %> signed-up
      </span>
    </div>
    <div class="span5 dummy-content" style="margin-left: 0;">
      <%= image_tag 'map_placeholder.png', :style => 'overflow:hidden;' %>
    </div>
  </div>

  <div class="row-fluid no-space">

    <div class="span8 subheader-content">
        <%= image_tag 'calendar.png', :align => "left", :width => '100px', :style => "padding-right: 10px; padding-bottom: 10px; margin-top: 7px;" %>
       <h3><%= @hackathon.name %></h3>
       <strong>Begins: </strong><%= @hackathon.start.to_formatted_s(:long) %><br>
       <strong>Ends: </strong><%= @hackathon.end.to_formatted_s(:long) %><br>
       <strong>Location: </strong><%= @hackathon.location %><br>
       <strong>Capacity: </strong><%= @hackathon.capacity %><br>
       <p id="hackathon-description">
        <%= @hackathon.description %><br>
       </p>
    </div>

    <div class="span4 subheader-content text-center">

    <% unless @hackathon.user_participating?(current_user) %>
      <%= form_for(@participant) do |f| %>
        <%= f.hidden_field :hackathon_id, :value => params[:id] %>
        <%= f.submit "Create Team", class: 'btn btn-primary btn-large' %>
      <% end %>
    <% end %>
     
    </div>
  </div>

</section>

<div class="clearfix"></div>

<section>

  <div class="row-fluid no-space">
  
    <% @hackathon.teams.each do |team| %>
      <div class="span3 team-content">
        <div class="well">
        <h3 class="tile-title">
          <%= team.name %>
        </h3>
        <h4>
          <% if team.project.present? %>
            <%= team.project %>
          <% else %>
            No project stated
          <% end %>
        </h4>
        <ul>
          <% team.teammates.each do |user| %>
          <li><%= link_to(User.find(user.user_id).name, "/users/#{user.user_id}") %></li>
          <% end %>
        </ul>
        <% unless @hackathon.teams.empty? || @hackathon.user_participating?(current_user) %>
          <%= link_to "JOIN", {:controller => "teammates", :action => "add_teammate", :team_id => team.id}, :method => :post, :class => "btn btn-info add_teammate" %>
<!--           <a href="/hackathons/<%#=@hackathon.id%>/teammates/new" class ='btn btn-info join_team'>JOIN</a> -->
        <% end %>
        <% if @hackathon.user_participating?(current_user) && team.teammates.any? { |user| user.user_id == current_user.id } %>
            <%= link_to "MY TEAM", "/hackathons/#{@hackathon.id}/teams/#{team.id}", :class => "btn btn-info" %>
        <% end %>
        </div>
      </div>
      <!-- for ever three team, put clearfix div -->

    <% end %>
  </div>

</section>
<!-- 


<h4>Pay Up!</h4>
<#%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $<#%= @hackathon.price %>.00</span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<#%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<#%= @hackathon.name %>"
          data-amount="<#%= @hackathon.price*100 %>"></script>
<#% end %> -->