config/routes.rb
Codewithus::Application.routes.draw do

  get 'signup'=> 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'skills_needed' => 'hackathons#skills_needed'

  get 'finish_account_signup' => "users#new_from_facebook"
  post 'finish_account_signup' => "users#create_from_facebook", :as => "finish_account_signup"

  post 'add_teammate' => 'teammates#add_teammate'

  match 'auth/facebook/callback', to: 'users#facebook_auth'
  get 'auth/failure', to: redirect('/')

  resources :users do 
    resources :user_skillcategories 
  end

  resources :hackathons do
    resources :teams
    resources :teammates
  end
  resources :sessions
  resources :charges
  resources :participants
  

  root :to => 'hackathons#index'

end

app/views/layouts/_about.html.erb
<h1>CodeWithUs</h1>
<p>Meet people around code.</p>
<br>
<p>Have a question? Want to share some feedback? Feel free to shoot us <%= link_to 'a message', 'https://github.com/andrewcallahan/codewithus/issues' %>. </p>
<hr>

<div id="built">
<p>Built <a href="http://www.flatironschool.com" target="_blank">@flatironschool</a></p>
<p> <a href="http://www.anthonywijnen.com" target="_blank">Anthony</a> | <a href="http://dolin.github.com" target="_blank">Danny</a> | <a href="http://andrewcallahan.github.com" target="_blank">Andrew</a> </p>
</div>

app/views/layouts/_footer.html.erb
      
      </div><!-- class="container-fluid" id="landing_page" -->
    
    </div><!-- class="row-fluid" -->
  <br>
  </body>

</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codewithus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-static-top">
    <div class="navbar inner wrapper">
      <div class="container">
        <ul class="nav nav-wrapper">
          <li class="active divider-vertical">
            <%= link_to image_tag('logo.png', :style => 'overflow:hidden; width: 80px'), root_path%>
          </li>
          <li class="divider-vertical"><%= link_to "hackathons", hackathons_path %></li>
          <li class="divider-vertical"><%= link_to "add hackathon", new_hackathon_path, class: "pull-right" %></li>
          <% if current_user %>
          <li class="divider-vertical"><%= link_to "profile", current_user, class: "pull-right" %></li>          
          <li class="divider-vertical"><%= link_to "logout", logout_path, class: "pull-right" %></li>
          <li class="divider-vertical"><%= link_to "Logged in as: #{current_user.name}", user_path(current_user), :class => "pull-right" %></li>
          <% else %>
            <li class="divider-vertical"><%= link_to "sign-up", signup_path, class: "pull-right" %></li>
            <li class="divider-vertical"><%= link_to "login", login_path, class: "pull-right" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

  <div class="container-fluid">

    <div class="row-fluid">


<!DOCTYPE html>
<html>
<head>
  <title>Codewithus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<script>
// $(document).ready(function(){
//   $('.divider-vertical').click(function(e){
//     if(!$(this).hasClass('active')){
//       $(this).addClass('active');
//     };
//   });
// });
</script>

  <div class="navbar navbar-static-top">
    <div class="navbar inner wrapper">

      <div class="container">
        <%= yield %>
      </div>

<%= render 'layouts/footer' %>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/landing_page.html.erb
<%= render 'layouts/header' %>

  <div class="container-fluid" id="landing_page">

    <div class="row-fluid">

      <div class="span12">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>

<%= render 'layouts/footer' %>